### ISSUE TITLE
Warning issues causing the validator to run extremely slowly.

### ISSUE THREAD

**Issue by VisLab** [hed-standard/hed-javascript#58] opened 2022-04-25 23:50 UTC
The warning of tag extensions reports every occurrence rather than once: It doesn't show location in the file --- just that it occurred. The message shows "102985 more files" have this problem.  In fact that, this number corresponds to the total number of occurrences of the issue across the dataset, not the number of files. This causes the validator to run extremely slowly.  How can we address?

>        3: [WARN] The validation on this HED string returned a warning. (code: 105 - HED_WARNING)
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ./sub-001/eeg/sub-001_task-AuditoryVisualShift_run-01_events.tsv
>                         Evidence: WARNING: [HED_TAG_EXTENDED] Tag extension found - "Think/Ignore"
>                 ... and 102985 more files having this issue (Use --verbose to see them all).
>

**Comment by happy5214** [comment] 2022-04-27 09:03
The `Issue` constructor in BIDS has a `line` parameter, but the line number is lost once the list of strings is extracted from the TSV files, before event-level validation even starts. I'll open up a separate issue for that, since that is something that should be fixed (and fixable).

The warnings being reported per-instance is by design, and that behavior is similar to other issues. The idea is to point out all occurrences of a problematic tag at once. However, if we're running into a dataset with 100k+ tag extensions, perhaps it would make more sense to collapse all of them into per-tag issues. I'm not sure the main hed-validator code is the place for that, as I think there's still a place for returning all of the issues individually (e.g. a verbose mode, which would require another parameter to the validator entry function), so perhaps the BIDS tie-in module (either within hed-validator or BIDS itself) could intercept tag extension issues and collapse them. I'll keep that discussion in this issue.

**Comment by VisLab** [comment] 2022-04-27 19:58
The tag is in the JSON sidecar and only appears once.  It should be reported once with the sidecar and not with each event file.

**Comment by happy5214** [comment] 2022-04-27 20:04
That would require the validator to check for extensions only in string-level validation, which is not currently possible because the `HED` column in TSVs currently does not undergo string-level validation. However, strings in that column probably should, so I'll open another issue for that.

**Closed** 2022-05-13 20:43 UTC
Labels: bids, validation
